#!/bin/bash
# Kaggle Git Push Helper
# Run this after the extraction script completes

echo "=================================="
echo "KAGGLE GIT PUSH SETUP"
echo "=================================="
echo ""
echo "You need a GitHub Personal Access Token (PAT)"
echo ""
echo "Steps:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Give it a name: 'Kaggle Notebook'"
echo "4. Select scopes: 'repo' (full control)"
echo "5. Generate and copy the token"
echo ""
echo "Then run these commands:"
echo ""
echo "# Set your token as environment variable"
echo "export GITHUB_TOKEN='your_token_here'"
echo ""
echo "# Push using token"
echo "cd /kaggle/working/amazon-ml-chal"
echo "git add KAGGLE_RUN_RESULTS.md"
echo "git commit -m 'Marqo extraction results'"
echo "git push https://\$GITHUB_TOKEN@github.com/observer04/amazon-ml-chal.git main"
echo ""
echo "=================================="
